import log from 'electron-log';
import fs, { writeJson } from 'fs-extra';
import path from 'node:path';
import ApmJson from '../lib/ApmJson';
import { getConfig } from '../lib/Config';
import { download, openDialog } from '../lib/ipcWrapper';
import { convertPackagesV2toV3 } from '../shared/convertPackagesV2toV3';
import { parsePackagesXml } from '../shared/parsePackagesXml';
import migration1to2 from './migration1to2';

const config = getConfig();

/**
 * Migration of common settings.
 * @returns {Promise<boolean>} True on successful completion
 */
async function global(): Promise<boolean> {
  const firstLaunch = !config.dataURL.hasMain();
  if (firstLaunch) {
    config.setDataVersion('3');
    return true;
  }

  // First, perform the previous migration.
  // false cancels startup
  if (!(await migration1to2.global())) return false;

  // Guard condition
  // The 'dataVersion' is always present due to previous migrations.
  // version: '2' or '3' or later
  const version = config.getDataVersion();
  if (version !== '2') return true;

  // Main
  log.info('Start migration: migration2to3.global())');

  // 1. Triggers initialization
  config.delete('modDate');
  config.delete('checkDate');
  config.delete('dataURL');

  // Finalize
  config.setDataVersion('3');
  await openDialog(
    'アップデート',
    'v2.x.xからv3.x.xへのアップデートに伴い、データ取得先がリセットされました。\nデフォルト以外のURLを設定していた場合は、再設定してください。',
    'info',
  );
  log.info('End of migration: migration2to3.global())');
  return true;
}

/**
 * Migration of the AviUtl installation folder.
 * @param {string} instPath - An installation path.
 */
async function byFolder(instPath: string) {
  const jsonPath = path.join(instPath, 'apm.json');
  const jsonExists = fs.existsSync(jsonPath);
  if (!jsonExists) return;

  await migration1to2.byFolder(instPath);

  // Guard condition
  // The 'dataVersion' is always present due to previous migrations.
  // version: '2' or '3' or later
  const apmJson = await ApmJson.load(instPath);
  const version = (await apmJson.get('dataVersion')) as string;
  if (version !== '2') return;

  // Main
  log.info(`Start migration: migration2to3.byFolder(${instPath})`);
  // packages の変換と dataVersion の更新を 1 回の書き込みで確定させる
  apmJson.begin();

  // 1. Backup apm.json
  await download(jsonPath, { subDir: 'migration2to3', keyText: jsonPath });

  // 2. Update the path to the online and local xml files.
  const packages = (await apmJson.get('packages')) as {
    [key: string]: { repository: string };
  };
  for (const id of Object.keys(packages)) {
    if (Object.hasOwn(packages[id], 'repository'))
      delete packages[id].repository;
  }
  await apmJson.set('packages', packages);

  // 3. Conversion of package.xml generated by the script installation function
  const packagesXML = path.join(instPath, 'packages.xml');
  if (fs.existsSync(packagesXML)) {
    // パース失敗は従来どおり呼び出し元へ伝播させる(try の外に置く)。
    // 変換・書き込みの失敗のみログに留めて続行する
    const packagesList = parsePackagesXml(
      fs.readFileSync(packagesXML, 'utf-8'),
    );

    try {
      const newData = convertPackagesV2toV3(Object.values(packagesList));
      await writeJson(path.join(instPath, 'packages.json'), newData);
    } catch (e) {
      log.error(e);
    }
  }

  // Finalize
  await apmJson.set('dataVersion', '3');
  await apmJson.commit();
  log.info(`End of migration: migration2to3.byFolder(${instPath})`);
}

const migration2to3 = {
  global,
  byFolder,
};
export default migration2to3;
