export const IPC_CHANNELS = {
  GET_APP_NAME: 'get-app-name',
  GET_APP_VERSION: 'get-app-version',
  APP_GET_PATH: 'app-get-path',
  APP_QUIT: 'app-quit',
  CHECK_UPDATE: 'check-update',
  OPEN_PATH: 'open-path',
  EXISTS_TEMP_FILE: 'exists-temp-file',
  OPEN_DIR_DIALOG: 'open-dir-dialog',
  OPEN_DIALOG: 'open-dialog',
  OPEN_YES_NO_DIALOG: 'open-yes-no-dialog',
  CLIPBOARD_WRITE_TEXT: 'clipboard-write-text',
  MIGRATION1TO2_CONFIRM_DIALOG: 'migration1to2-confirm-dialog',
  MIGRATION1TO2_DATAURL_INPUT_DIALOG: 'migration1to2-dataurl-input-dialog',
  DOWNLOAD: 'download',
  OPEN_BROWSER: 'open-browser',
};
